# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EckDiagnosticsParser < Formula
  desc ""
  homepage "https://github.com/framsouza/eck-diagnostics-parser"
  version "1.0.0"

  on_macos do
    url "https://github.com/framsouza/eck-diagnostics-parser/releases/download/v1.0.0/eck-diagnostics-parser_1.0.0_darwin_all.tar.gz"
    sha256 "d4bdbe8f99232e428c2d2d38eaeb8542a6884f6c930efe803c1be93cc16c7132"

    def install
      bin.install "eck-diagnostics-parser"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/framsouza/eck-diagnostics-parser/releases/download/v1.0.0/eck-diagnostics-parser_1.0.0_linux_arm64.tar.gz"
      sha256 "6d964607d2384f4458c13d7c17d8a12762269d370174a640169636013373c960"

      def install
        bin.install "eck-diagnostics-parser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/framsouza/eck-diagnostics-parser/releases/download/v1.0.0/eck-diagnostics-parser_1.0.0_linux_amd64.tar.gz"
      sha256 "9f66f3d2f59574afe595a3df2cdbdf1554545aff3a4f0f1c184a11e64726932c"

      def install
        bin.install "eck-diagnostics-parser"
      end
    end
  end
end
