# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EckDiagnosticsParser < Formula
  desc ""
  homepage "https://github.com/framsouza/eck-diagnostics-parser"
  version "1.0.2"

  on_macos do
    url "https://github.com/framsouza/eck-diagnostics-parser/releases/download/v1.0.2/eck-diagnostics-parser_1.0.2_darwin_all.tar.gz"
    sha256 "e1b424e2c627f5127f3784391b6996743089f96fb341719ab7ef8a1228f5b819"

    def install
      bin.install "eck-diagnostics-parser"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/framsouza/eck-diagnostics-parser/releases/download/v1.0.2/eck-diagnostics-parser_1.0.2_linux_arm64.tar.gz"
      sha256 "71e8f709a0236c32d32fd9b5e9b41159649049e9d81a3346f9179cdee9e46801"

      def install
        bin.install "eck-diagnostics-parser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/framsouza/eck-diagnostics-parser/releases/download/v1.0.2/eck-diagnostics-parser_1.0.2_linux_amd64.tar.gz"
      sha256 "f7b9893f6dfa71bcdd3fcb6a13c1b943042aba139603664ee817b7d93dbacebf"

      def install
        bin.install "eck-diagnostics-parser"
      end
    end
  end
end
